// Material
import {
  MatButtonModule,
  MatCheckboxModule,
  MatToolbarModule,
  MatIconModule,
  MatDividerModule,
  MatListModule,
  MatCardModule,
  MatExpansionModule,
  MatRadioModule,
  MatGridListModule,
  MatTabsModule,
  MatSnackBarModule,
  MatProgressSpinnerModule,
  MatSelectModule,
  MatSidenavModule,
  MatMenuModule,
  MatSlideToggleModule,
  MatDialogModule,
  MatFormFieldModule,
  MatInputModule,
  MatProgressBarModule,
  MatStepperModule,
  MatBadgeModule
} from '@angular/material';

export const materialModules = [
  MatButtonModule,
  MatCheckboxModule,
  MatToolbarModule,
  MatIconModule,
  MatDividerModule, 
  MatListModule,
  MatCardModule,
  MatExpansionModule,
  MatRadioModule,
  MatGridListModule,
  MatTabsModule,
  MatSnackBarModule,
  MatProgressSpinnerModule,
  MatSelectModule,
  MatSidenavModule,
  MatMenuModule,
  MatSlideToggleModule,
  MatDialogModule,
  MatFormFieldModule,
  MatInputModule,
  MatProgressBarModule,
  MatStepperModule,
  MatBadgeModule
];
